wgetpaste-2.13

diff --git a/wgetpaste b/wgetpaste
--- a/wgetpaste
+++ b/wgetpaste
@@ -4,7 +4,7 @@
 # Copyright (c) 2007 Bo Ørsted Andresen <bo.andresen@zlin.dk>
 # Distributed as-is. With no warranties.
 
-VERSION="2.12"
+VERSION="2.13"
 
 # don't inherit LANGUAGE from the env
 unset LANGUAGE
@@ -264,7 +264,7 @@ Usage: $0 [options] [file[s]]
 Options:
     -l, --language LANG           set language (defaults to "$DEFAULT_LANGUAGE")
     -d, --description DESCRIPTION set description (defaults to "stdin" or filename)
-    -n, --nick NICK               set nick (defaults to your username))
+    -n, --nick NICK               set nick (defaults to your username)
     -s, --service SERVICE         set service to use (defaults to "$DEFAULT_SERVICE")
     -e, --expiration EXPIRATION   set when it should expire (defaults to "$DEFAULT_EXPIRATION")
 
@@ -284,6 +284,7 @@ Options:
     -r, --raw                     show url for the raw paste (no syntax highlighting or html)
     -t, --tee                     use tee to show what is being pasted
     -v, --verbose                 show wget stderr output if no url is received
+        --completions             emit output suitable for shell completions (only affects --list-*)
         --debug                   be *very* verbose (implies -v)
 
     -h, --help                    show this help
@@ -297,8 +298,18 @@ EOF
 }
 
 showservices() {
-	echo "Services supported: (case sensitive):"
 	local max s IND INDV engine url d
+	if [[ -n $COMPLETIONS ]]; then
+		for s in $SERVICES; do
+			if [[ -n $VERBOSE ]]; then
+				d=URL_$s && echo "$s:${!d% *}"
+			else
+				echo "$s"
+			fi
+		done
+		exit 0
+	fi
+	echo "Services supported: (case sensitive):"
 	max=4
 	for s in $SERVICES; do
 		[[ ${#s} -gt $max ]] && max=${#s}
@@ -325,10 +336,18 @@ showservices() {
 	done | sort
 }
 
+printlist() {
+	while [[ -n $1 ]]; do
+		echo "${1//\%/ }"
+		shift
+	done
+}
+
 showlanguages() {
-	echo "Languages supported by $(getrecipient) (case sensitive):"
 	local l lang d
 	lang=LANGUAGES_$ENGINE
+	[[ -n $COMPLETIONS ]] && printlist ${!lang} | sort && exit 0
+	echo "Languages supported by $(getrecipient) (case sensitive):"
 	[[ -z ${!lang} ]] && echo "$N\"$ENGINE\" has no support for setting language." >&2 && exit 1
 	for l in ${!lang}; do
 		[[ ${l//\%/ } = $DEFAULT_LANGUAGE ]] && d="*" || d=" "
@@ -337,9 +356,10 @@ showlanguages() {
 }
 
 showexpirations() {
-	echo "Expiration options supported by $(getrecipient) (case sensitive):"
 	local e expiration info d
 	expiration=EXPIRATIONS_$ENGINE
+	[[ -n $COMPLETIONS ]] && printlist ${!expiration} && exit 0
+	echo "Expiration options supported by $(getrecipient) (case sensitive):"
 	info=EXPIRATION_INFO_$SERVICE
 	[[ -z ${!expiration} ]] && echo "$N${!info}\"$ENGINE\" has no support for setting expiration." >&2 && exit 1
 	for e in ${!expiration}; do
@@ -350,23 +370,15 @@ showexpirations() {
 
 showurl() {
 	echo "Your ${2}paste can be seen here: $1"
-	[[ $XPASTE ]] && x_paste "$1"
-	[[ $XCLIPPASTE ]] && x_clip_paste "$1"
+	[[ $XPASTE ]] && x_paste "$1" primary
+	[[ $XCLIPPASTE ]] && x_paste "$1" clipboard
 }
 
 x_paste() {
 	if [[ -x $(type -P xclip) ]]; then
-		echo -n "$*" | xclip -selection primary -loops 10 &>/dev/null || die "xclip failed."
+		echo -n "$1" | xclip -selection $2 -loops 10 &>/dev/null || die "xclip failed."
 	else
 		noxclip paste "write to"
-	fi
-}
-
-x_clip_paste() {
-	if [[ -x $(type -P xclip) ]]; then
-		echo -n "$*" | xclip -selection clipboard -loops 10 &>/dev/null || die "xclip failed."
-	else
-		noxclip clip_paste "write to"
 	fi
 }
 
@@ -471,6 +483,9 @@ while [[ -n $1 ]]; do
 		SOURCE="command"
 		COMMANDS[${#COMMANDS[*]}]="$2"
 		;;
+		--completions )
+		COMPLETIONS=0
+		;;
 		-d | --description )
 		requiredarg "$@"
 		DESCRIPTION="$2"
@@ -556,11 +571,10 @@ load_configs() {
 		for f in {/etc/,~/.}wgetpaste{.d/*.bash,}; do
 			if [[ -f $f ]]; then
 				if [[ -z $deprecated ]]; then
-					echo "The config files for wgetpaste have changed to *.conf." >&2
-					echo >&2
+					echo "The config files for wgetpaste have changed to *.conf.$N" >&2
 					deprecated=0
 				fi
-				echo "Please move ${f} to ${f%.bash}.conf" >&2
+				echo "Please move ${f} to ${f/%.bash/.conf}" >&2
 				source "$f" || die "Failed to source $f"
 			fi
 		done
